### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by 13loops** [Xenko/BeachBall#2]
I'm sure that the redundakitty timer and autoclicker is broken. I'm not really sure about the other features and the beta, as I haven't really had the chance to use it. Some of the beta must be affected at least (logicat solver, monty haul, etc.) by the kitty problem, or may be broken themselves.

**Comment by Guizmus** [comment]
Should be resolved in the last beta commit. Needs final testing before deployment.

**Comment by Guizmus** [comment]
Should now be solved.

**Comment by 13loops** [comment]
How exactly do you toggle beachball settings?

**Comment by 13loops** [comment]
This is probably something that should be written into the readme.

**Comment by 13loops** [comment]
(I hadn't used this specific script, but they all would have definitely had
the same problem.)

**Comment by Guizmus** [comment]
BeachBall settings are in the "Option" panel, the same you find in the game, at the bottom.
You can toggle it on and off from there.

And you are right, I'll add it in the wiki soon.
